### ISSUE TITLE
10 sample articles for meeting

### ISSUE THREAD

**Issue by tom95** [Moby-City/efrei-pfe2017-influence#6]
* [x] Corinna: Le Monde, Le Figaro
* [x] Tom: carenews.com
* [x] Michael: ulule.com
* [ ] Julian: paris.fr
* [ ] Björn: Facebook

**Comment by moikipoiki** [comment]
Ulule.com:
usually short-term projects. Has standardized API for retrieving data. Unclear how to find creator of projects.
https://fr.ulule.com/potable-water-cambodia/
https://www.ulule.com/united-schools/

**Comment by tom95** [comment]
**carenews.com:**
* list of French non-profits, all associated with at least one article and a general description (515? associations)
* often contains link to official Facebook account
* discover/search by domain/cause (human rights, environment, ...), country, job offers
* mainly focused around articles concerning a specific non-profit
  - announcements of achievements (http://www.carenews.com/fr/news/9017-chiffres-30-grandes-ecoles-levent-100-millions-d-euros)
  - appeals (http://www.carenews.com/fr/news/9172-appel-a-projets-de-la-fondation-auchan-pour-la-jeunesse)
  - general news (https://www.carenews.com/fr/news/9171-l-institut-telemaque-lance-sa-plateforme-mon-avenir-en-grand)
  - possible re-posts (http://www.carenews.com/fr/news/9157-en-images-une-video-de-save-the-children-denonce-le-mariage-force-des-mineurs)

**Comment by corinnaj** [comment]
Le Figaro and Le Monde:
A subscription is required to access all articles in full length.
**Le Monde:**
http://www.lemonde.fr/syrie/article/2017/10/25/enfants-malnutris-dans-la-ghouta-pres-de-damas-nous-reclamons-un-acces-humanitaire_5205815_1618247.html?xtmc=associations&xtcr=20 (article about Unicef)
http://www.lemonde.fr/afrique/article/2017/10/20/quatre-ong-de-solidarite-claquent-la-porte-des-etats-generaux-de-l-alimentation_5203870_3212.html?xtmc=associations&xtcr=51 (multiple NGOs)

**Le Figaro:**
http://video.lefigaro.fr/figaro/video/des-modeles-handicapees-defilent-a-la-fashion-week-de-moscou/5379107947001/ (video about russion non-profit)
http://www.lefigaro.fr/flash-actu/2017/10/13/97001-20171013FILWWW00258-pedophilieeglise-une-association-veut-des-reformes.php (article about a french non-profit)
http://www.lefigaro.fr/conjoncture/2016/10/07/20002-20161007ARTFIG00302-les-associations-auront-aussi-droit-a-une-baisse-des-charges.php (article for non-profits)
